service: sinote

plugins:
  - serverless-offline

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - X-Amz-Date
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
    - app_user_id
    - app_user_name

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: dev
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    NOTES_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NOTES_TABLE}'

functions:
  # category endpoint
  get-category:
    handler: api/category/get-category.handler
    description: GET /categories/{categoryId}
    events:
      - http:
          path: categories/{categoryId}
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  get-categories:
    handler: api/category/get-categories.handler
    description: GET /categories
    events:
      - http:
          path: categories
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  create-category:
    handler: api/category/create-category.handler
    description: POST /category
    events:
      - http:
          path: categories
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  update-category:
    handler: api/category/update-category.handler
    description: PATCH /categories/{categoryId}
    events:
      - http:
          path: categories/{categoryId}
          method: patch
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  delete-category:
    handler: api/category/delete-category.handler
    description: DELETE /categories/{categoryId}
    events:
      - http:
          path: categories/{categoryId}
          method: delete
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  # tag endpoint
  get-tag:
    handler: api/tag/get-tag.handler
    description: GET /tags/{tagId}
    events:
      - http:
          path: tags/{tagId}
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  get-tags:
    handler: api/tag/get-tags.handler
    description: GET /tags
    events:
      - http:
          path: tags
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  create-tag:
    handler: api/tag/create-tag.handler
    description: POST /tags
    events:
      - http:
          path: tags
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  # note endpoint
  get-note:
    handler: api/note/get-note.handler
    description: GET /notes/{noteId}
    events:
      - http:
          path: notes/{noteId}
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  get-notes:
    handler: api/note/get-notes.handler
    description: GET /notes
    events:
      - http:
          path: notes
          method: get
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  create-note:
    handler: api/note/create-note.handler
    description: POST /notes
    events:
      - http:
          path: notes
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  update-note:
    handler: api/note/update-note.handler
    description: PATCH /notes/{noteId}
    events:
      - http:
          path: notes/{noteId}
          method: patch
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  change-note-category:
    handler: api/note/change-category.handler
    description: POST /notes/{noteId}/change-note-cate
    events:
      - http:
          path: notes/{noteId}/change-note-cate
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  delete-note:
    handler: api/note/delete-note.handler
    description: DELETE /notes/{noteId}
    events:
      - http:
          path: notes/{noteId}
          method: delete
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  attach-tag:
    handler: api/note/attach-tag.handler
    description: POST /notes/{noteId}/attach-tag
    events:
      - http:
          path: notes/{noteId}/attach-tag
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

  unattach-tag:
    handler: api/note/unattach-tag.handler
    description: POST /notes/{noteId}/unattach-tag
    events:
      - http:
          path: notes/{noteId}/unattach-tag
          method: post
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.NOTES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: relationship_id
            AttributeType: S
          - AttributeName: create_timestamp
            AttributeType: S
          - AttributeName: update_timestamp
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: relationship_id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: create_time-index
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: create_timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: update_time-index
            KeySchema:
              - AttributeName: id
                KeyType: HASH
              - AttributeName: update_timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: user-index
            KeySchema:
              - AttributeName: user_id
                KeyType: HASH
              - AttributeName: update_timestamp
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
